---
name: Tests
on:
  pull_request: ~
  push:
    branches:
      - main

permissions: read-all

jobs:
  build:
    strategy:
      matrix:
        neovim_version:
          - "nightly"
          - "stable"

    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run tests
        uses: nvim-neorocks/nvim-busted-action@v1
        with:
          nvim_version: ${{ matrix.neovim_version }}
